version: "2"

services:

  web:
    build: .
    networks:
      - cybernet
    ports:
      - "3000:3000"
    env_file:
      - genome-explorer.env
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - genome-explorer-env
    networks:
      - cybernet
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  cybernet:
